[package]
name = "acdc-egg"
version = "0.1.0"
edition = "2024"

[dependencies]
egg = "0.10.0"
env_logger = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
log = "0.4.26"